---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autopulse-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: autopulse-configmap
            items:
              - key: config.yaml
                templateAs: Values
  dataFrom:
    - extract:
        key: autopulse
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autopulse-db-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: autopulse_main
        INIT_POSTGRES_HOST: postgres-v15-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTOPULSE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTOPULSE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: autopulse
    - extract:
        key: cloudnative-pg
